CREATE OR REPLACE TABLE LES_ASSOCIATIONS 
(
   ID_ASSOCIATION    INTEGER AUTO_INCREMENT PRIMARY KEY,
   NOM               VARCHAR (255) NOT NULL,
   EMAIL             VARCHAR (255) NOT NULL,
   MOT_DE_PASSE      VARCHAR (255) NOT NULL,
   PHONE_NUMBER      NUMERIC     NOT  NULL,
   DATE            TIMESTAMP    NOT NULL,
   ADRESS           VARCHAR (255) NOT  NULL
);

CREATE OR REPLACE TABLE LES_MEMBRES 
(
   ID_MEMBERS        INTEGER AUTO_INCREMENT PRIMARY KEY,
   NOM               VARCHAR (255) NOT  NULL,
   PHONE_NUMBER      NUMERIC      NOT NULL,
   EMAIL             VARCHAR (255) NOT  NULL,
   MOT_DE_PASSE      VARCHAR (255) NOT  NULL,
   DATE            TIMESTAMP    NOT NULL,
   TYPE_MEMBERS      SMALLINT   NOT NULL,
   ADRESS            VARCHAR (255) NOT  NULL
);

CREATE OR REPLACE TABLE LES_ACTIVITES 
(
   ID_ACTIVITES      INTEGER AUTO_INCREMENT PRIMARY KEY,
   ID_MEMBERS        INTEGER NOT NULL,
   OBJECT            VARCHAR (255) NOT  NULL,
   CONTENU           VARCHAR (255) NOT NULL,
   DATE            TIMESTAMP    NOT NULL,
   CONSTRAINT FK_ACTIVITES_MEMBRES FOREIGN KEY (ID_MEMBERS) REFERENCES LES_MEMBRES (ID_MEMBERS)
);

CREATE OR REPLACE TABLE ACTIVITE_IMAGE 
(
   ID_ACTIVITE_IMAGE  INTEGER AUTO_INCREMENT PRIMARY KEY,
   ID_ACTIVITES       INTEGER NOT NULL,
   URL_IMAGE          VARCHAR (255) NOT NULL,
   DATE            TIMESTAMP    NOT NULL,
   CONSTRAINT FK_IMAGE_ACTIVITE FOREIGN KEY (ID_ACTIVITES) REFERENCES LES_ACTIVITES (ID_ACTIVITES)
);

CREATE OR REPLACE TABLE BENEVOLE 
(
   ID_BENEVOL        INTEGER AUTO_INCREMENT PRIMARY KEY,
   NOM              VARCHAR (255) NOT NULL,
   EMAIL              VARCHAR (255) NOT NULL,
   PHONE_NUMBER      NUMERIC     NOT  NULL,
   MOT_DE_PASSE       VARCHAR (255) NOT NULL,
   DATE           TIMESTAMP   NOT  NULL,
   ADRESS            VARCHAR (255) NOT NULL
);
